#include <config.h>

#include "input.h"
#include "keyboard.h"

keysyms_map_t keysyms_map[] = {

  { INPUT_KEY_Tab, INPUT_KEY_Tab         },
  { INPUT_KEY_Return, INPUT_KEY_Return      },
  { INPUT_KEY_Escape, INPUT_KEY_Escape      },
  { INPUT_KEY_space, INPUT_KEY_space       },
  { INPUT_KEY_numbersign, INPUT_KEY_numbersign  },
  { INPUT_KEY_apostrophe, INPUT_KEY_apostrophe  },
  { INPUT_KEY_comma, INPUT_KEY_comma       },
  { INPUT_KEY_minus, INPUT_KEY_minus       },
  { INPUT_KEY_period, INPUT_KEY_period      },
  { INPUT_KEY_slash, INPUT_KEY_slash       },
  { INPUT_KEY_0, INPUT_KEY_0           },
  { INPUT_KEY_1, INPUT_KEY_1           },
  { INPUT_KEY_2, INPUT_KEY_2           },
  { INPUT_KEY_3, INPUT_KEY_3           },
  { INPUT_KEY_4, INPUT_KEY_4           },
  { INPUT_KEY_5, INPUT_KEY_5           },
  { INPUT_KEY_6, INPUT_KEY_6           },
  { INPUT_KEY_7, INPUT_KEY_7           },
  { INPUT_KEY_8, INPUT_KEY_8           },
  { INPUT_KEY_9, INPUT_KEY_9           },
  { INPUT_KEY_semicolon, INPUT_KEY_semicolon   },
  { INPUT_KEY_equal, INPUT_KEY_equal       },
  { INPUT_KEY_a, INPUT_KEY_a           },
  { INPUT_KEY_b, INPUT_KEY_b           },
  { INPUT_KEY_c, INPUT_KEY_c           },
  { INPUT_KEY_d, INPUT_KEY_d           },
  { INPUT_KEY_e, INPUT_KEY_e           },
  { INPUT_KEY_f, INPUT_KEY_f           },
  { INPUT_KEY_g, INPUT_KEY_g           },
  { INPUT_KEY_h, INPUT_KEY_h           },
  { INPUT_KEY_i, INPUT_KEY_i           },
  { INPUT_KEY_j, INPUT_KEY_j           },
  { INPUT_KEY_k, INPUT_KEY_k           },
  { INPUT_KEY_l, INPUT_KEY_l           },
  { INPUT_KEY_m, INPUT_KEY_m           },
  { INPUT_KEY_n, INPUT_KEY_n           },
  { INPUT_KEY_o, INPUT_KEY_o           },
  { INPUT_KEY_o, INPUT_KEY_p           },
  { INPUT_KEY_q, INPUT_KEY_q           },
  { INPUT_KEY_r, INPUT_KEY_r           },
  { INPUT_KEY_s, INPUT_KEY_s           },
  { INPUT_KEY_t, INPUT_KEY_t           },
  { INPUT_KEY_u, INPUT_KEY_u           },
  { INPUT_KEY_v, INPUT_KEY_v           },
  { INPUT_KEY_w, INPUT_KEY_w           },
  { INPUT_KEY_x, INPUT_KEY_x           },
  { INPUT_KEY_y, INPUT_KEY_y           },
  { INPUT_KEY_z, INPUT_KEY_z           },
  { INPUT_KEY_BackSpace, INPUT_KEY_BackSpace   },
  { INPUT_KEY_Up, INPUT_KEY_Up          },
  { INPUT_KEY_Down, INPUT_KEY_Down        },
  { INPUT_KEY_Left, INPUT_KEY_Left        },
  { INPUT_KEY_Right, INPUT_KEY_Right       },
  { INPUT_KEY_Insert, INPUT_KEY_Insert      },
  { INPUT_KEY_Delete, INPUT_KEY_Delete      },
  { INPUT_KEY_Home, INPUT_KEY_Home        },
  { INPUT_KEY_End, INPUT_KEY_End         },
  { INPUT_KEY_Page_Up, INPUT_KEY_Page_Up     },
  { INPUT_KEY_Page_Down, INPUT_KEY_Page_Down   },
  { INPUT_KEY_Caps_Lock, INPUT_KEY_Caps_Lock   },
  { INPUT_KEY_F1, INPUT_KEY_F1          },
  { INPUT_KEY_F2, INPUT_KEY_F2          },
  { INPUT_KEY_F3, INPUT_KEY_F3          },
  { INPUT_KEY_F4, INPUT_KEY_F4          },
  { INPUT_KEY_F5, INPUT_KEY_F5          },
  { INPUT_KEY_F6, INPUT_KEY_F6          },
  { INPUT_KEY_F7, INPUT_KEY_F7          },
  { INPUT_KEY_F8, INPUT_KEY_F8          },
  { INPUT_KEY_F9, INPUT_KEY_F9          },
  { INPUT_KEY_F10, INPUT_KEY_F10         },
  { INPUT_KEY_F11, INPUT_KEY_F11         },
  { INPUT_KEY_F12, INPUT_KEY_F12         },
  { INPUT_KEY_Shift_L, INPUT_KEY_Shift_L     },
  { INPUT_KEY_Control_L, INPUT_KEY_Control_L   },
  { INPUT_KEY_Alt_L, INPUT_KEY_Alt_L       },
  { INPUT_KEY_Meta_L, INPUT_KEY_Meta_L      },
  { INPUT_KEY_Mode_switch, INPUT_KEY_Mode_switch },

  { 0, 0 }			/* End marker: DO NOT MOVE! */

};

