#include <config.h>

#include "input.h"
#include "keyboard.h"

keysyms_map_t keysyms_map[] = {

  { 0, INPUT_KEY_Tab         },
  { 0, INPUT_KEY_Return      },
  { 0, INPUT_KEY_Escape      },
  { 0, INPUT_KEY_space       },
  { 0, INPUT_KEY_numbersign  },
  { 0, INPUT_KEY_apostrophe  },
  { 0, INPUT_KEY_comma       },
  { 0, INPUT_KEY_minus       },
  { 0, INPUT_KEY_period      },
  { 0, INPUT_KEY_slash       },
  { 0, INPUT_KEY_0           },
  { 0, INPUT_KEY_1           },
  { 0, INPUT_KEY_2           },
  { 0, INPUT_KEY_3           },
  { 0, INPUT_KEY_4           },
  { 0, INPUT_KEY_5           },
  { 0, INPUT_KEY_6           },
  { 0, INPUT_KEY_7           },
  { 0, INPUT_KEY_8           },
  { 0, INPUT_KEY_9           },
  { 0, INPUT_KEY_semicolon   },
  { 0, INPUT_KEY_equal       },
  { 0, INPUT_KEY_a           },
  { 0, INPUT_KEY_b           },
  { 0, INPUT_KEY_c           },
  { 0, INPUT_KEY_d           },
  { 0, INPUT_KEY_e           },
  { 0, INPUT_KEY_f           },
  { 0, INPUT_KEY_g           },
  { 0, INPUT_KEY_h           },
  { 0, INPUT_KEY_i           },
  { 0, INPUT_KEY_j           },
  { 0, INPUT_KEY_k           },
  { 0, INPUT_KEY_l           },
  { 0, INPUT_KEY_m           },
  { 0, INPUT_KEY_n           },
  { 0, INPUT_KEY_o           },
  { 0, INPUT_KEY_p           },
  { 0, INPUT_KEY_q           },
  { 0, INPUT_KEY_r           },
  { 0, INPUT_KEY_s           },
  { 0, INPUT_KEY_t           },
  { 0, INPUT_KEY_u           },
  { 0, INPUT_KEY_v           },
  { 0, INPUT_KEY_w           },
  { 0, INPUT_KEY_x           },
  { 0, INPUT_KEY_y           },
  { 0, INPUT_KEY_z           },
  { 0, INPUT_KEY_BackSpace   },
  { 0, INPUT_KEY_Up          },
  { 0, INPUT_KEY_Down        },
  { 0, INPUT_KEY_Left        },
  { 0, INPUT_KEY_Right       },
  { 0, INPUT_KEY_Insert      },
  { 0, INPUT_KEY_Delete      },
  { 0, INPUT_KEY_Home        },
  { 0, INPUT_KEY_End         },
  { 0, INPUT_KEY_Page_Up     },
  { 0, INPUT_KEY_Page_Down   },
  { 0, INPUT_KEY_Caps_Lock   },
  { 0, INPUT_KEY_F1          },
  { 0, INPUT_KEY_F2          },
  { 0, INPUT_KEY_F3          },
  { 0, INPUT_KEY_F4          },
  { 0, INPUT_KEY_F5          },
  { 0, INPUT_KEY_F6          },
  { 0, INPUT_KEY_F7          },
  { 0, INPUT_KEY_F8          },
  { 0, INPUT_KEY_F9          },
  { 0, INPUT_KEY_F10         },
  { 0, INPUT_KEY_F11         },
  { 0, INPUT_KEY_F12         },
  { 0, INPUT_KEY_Shift_L     },
  { 0, INPUT_KEY_Control_L   },
  { 0, INPUT_KEY_Alt_L       },
  { 0, INPUT_KEY_Meta_L      },
  { 0, INPUT_KEY_Mode_switch },

  { 0, 0 }			/* End marker: DO NOT MOVE! */

};

