PSPSDK=$(shell psp-config --pspsdk-path)

PSPAPP=psp
LSP=aux/libspectrum
L765=aux/lib765
PSPLIB=ui/psp/lib
MZLIB=mzlib

PSP_FW_VERSION=200
export PSP_FW_VERSION

PSP_APP_NAME=Fuse PSP
PSP_APP_VER=0.9.0.2

TARGET=fusepsp
EXTRA_TARGETS=EBOOT.PBP
PSP_EBOOT_TITLE=$(PSP_APP_NAME) $(PSP_APP_VER)
PSP_EBOOT_ICON=ui/psp/fuse-icon.png

BUILD_LS=$(LSP)/creator.o $(LSP)/crypto.o $(LSP)/csw.o \
         $(LSP)/bzip2.o $(LSP)/dck.o $(LSP)/ide.o \
         $(LSP)/libspectrum.o $(LSP)/microdrive.o $(LSP)/plusd.o \
         $(LSP)/rzx.o $(LSP)/sna.o $(LSP)/snap_accessors.o \
         $(LSP)/snapshot.o $(LSP)/snp.o $(LSP)/sp.o \
         $(LSP)/symbol_table.o $(LSP)/szx.o $(LSP)/tap.o \
         $(LSP)/tape_accessors.o $(LSP)/tape_block.o $(LSP)/tape.o \
         $(LSP)/tape_set.o $(LSP)/timings.o $(LSP)/tzx_read.o \
         $(LSP)/tzx_write.o $(LSP)/warajevo_read.o $(LSP)/wav.o \
         $(LSP)/z80.o $(LSP)/z80em.o $(LSP)/zlib.o $(LSP)/zxs.o \
         $(LSP)/myglib/ghash.o $(LSP)/myglib/gslist.o
BUILD_765=$(L765)/lib/765drive.o $(L765)/lib/765dsk.o $(L765)/lib/765fdc.o \
          $(L765)/lib/765ldsk.o $(L765)/lib/error.o
BUILD_FUSE=debugger/breakpoint.o debugger/command.o debugger/commandl.o \
           debugger/commandy.o debugger/debugger.o debugger/disassemble.o \
           debugger/expression.o \
           z80/z80.o z80/z80_ops.o \
           pokefinder/pokefinder.o \
           machines/pentagon1024.o machines/pentagon512.o machines/pentagon.o \
           machines/scorpion.o machines/spec128.o machines/spec16.o \
           machines/spec48.o machines/specplus2a.o machines/specplus2.o \
           machines/specplus3.o machines/specplus3e.o machines/spec_se.o \
           machines/tc2048.o machines/tc2068.o machines/ts2068.o \
           disk/beta.o disk/crc.o disk/disk.o disk/fdd.o disk/plusd.o \
           disk/wd_fdc.o \
           ay.o dck.o display.o divide.o ide.o if1.o \
           if2.o input.o joystick.o kempmouse.o keyboard.o loader.o \
           machine.o memory.o module.o periph.o printer.o profile.o \
           psg.o scld.o screenshot.o settings.o simpleide.o slt.o \
           snapshot.o sound.o ui.o uidisplay.o ula.o utils.o zxatasp.o \
           zxcf.o timer/timer.o event.o rzx.o spectrum.o tape.o \
           fuse.o \
           compat/dirname.o \
           ui/scaler/scaler.o ui/scaler/scalers16.o ui/scaler/scalers32.o \
           sound/sfifo.o
BUILD_PORT=ui/psp/keysyms.o timer/psp.o ui/psp/paths.o ui/psp/osname.o \
           ui/psp/pspui.o ui/psp/pspdisplay.o ui/psp/debugger.o ui/psp/statusbar.o \
           sound/pspsound.o ui/psp/pspjoystick.o
BUILD_MZ=$(MZLIB)/ioapi.o $(MZLIB)/unzip.o


OBJS=$(BUILD_LS) $(BUILD_FUSE) $(BUILD_PORT) $(BUILD_MZ) $(BUILD_765)

DEFINES=-DFUSEDATADIR="\"system\"" -DSOUND_BUFFER_SIZE=368 -DPSP_DEBUG \
        -DPATH_MAX=2048
BASE_DEFS=-DPSP -DPSP_APP_VER=\"$(PSP_APP_VER)\" -DPSP_APP_NAME="\"$(PSP_APP_NAME)\""
CFLAGS=-O2 -G0 -Wall $(BASE_DEFS) $(DEFINES)
CXXFLAGS=$(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS=$(CFLAGS)
INCDIR=. $(PSPLIB) $(LSP) $(MZLIB) $(L765)/include psp
LIBDIR=$(PSPLIB)
LIBS=-lpsplib -lpng -lpspgu -lpsppower -lz -lm -lc -lpspaudio -lpsprtc \
     -lpspwlan -lpspnet_adhoc -lpspnet_adhocctl -lpspnet_adhocmatching

all: build_psplib
clean: clean_psplib

include $(PSPSDK)/lib/build.mak

build_psplib:
	cd $(PSPLIB) ; $(MAKE)

clean_psplib:
	cd $(PSPLIB) ; $(MAKE) clean
