CC=psp-gcc
AR=psp-ar
RANLIB=psp-ranlib
RM=rm -rf
PSPSDK=$(shell psp-config --pspsdk-path)
CFLAGS=-G0 -O2 -Wall -DPSP -DHAVE_ZLIB_H -I$(PSPSDK)/include -I../../ -I./

all: libspectrum.a

libspectrum.a: \
         creator.o crypto.o csw.o \
         bzip2.o dck.o ide.o memory.o \
         libspectrum.o microdrive.o plusd.o \
         rzx.o sna.o snap_accessors.o \
         snapshot.o snp.o sp.o \
         symbol_table.o szx.o tap.o \
         tape_accessors.o tape_block.o tape.o \
         tape_set.o timings.o tzx_read.o \
         tzx_write.o warajevo_read.o wav.o \
         z80.o z80em.o zlib.o zxs.o \
         myglib/garray.o myglib/ghash.o myglib/gslist.o
	$(AR) cru $@ $?
	$(RANLIB) $@

clean:
	$(RM) *.o myglib/*.o *.a
